### ISSUE TITLE
Get the number of unsealed and unsealing file count

### ISSUE THREAD

**Issue by DImuthuUpe** [NASA-IMPACT/HLS-Transfer-Catalog#10]
For controlling the rate of unsealing, we need an endpoint like below

http://127.0.0.1:5000/catalogue/count/?transfer_status=NOT_STARTED&sealed_State=unsealing

This should return the number of files that satisfy the filtering criteria.

**Comment by NISH1001** [comment]
Thanks, Dimuthu, we'll look into this...

**Comment by ub0005** [comment]
@DImuthuUpe The endpoint needed is added to pushed into the **feature/cold-storage-files-implementation** branch
