### ISSUE TITLE
Storage ids in catalog entity

### ISSUE THREAD

**Issue by DImuthuUpe** [NASA-IMPACT/HLS-Transfer-Catalog#11]
There might be different source containers and destination buckets for multiple datasets. So we need two additional columns with source_storage_id and dest_storage_id. These values should be passed in the csv bulk upload as well

**Comment by ub0005** [comment]
@DImuthuUpe what needs to be done if the value is empty for source_storage_id and dest_storage_id in the incoming CSV file?

Do we need to throw an error or input the value as empty string the database ?

cc: @NISH1001

**Comment by DImuthuUpe** [comment]
@ub0005 This should throw an error. I think it is better to enforce these rules at the database schema level as not-null fields. Then you do not need to handle them at the API manually

**Comment by ub0005** [comment]
@DImuthuUpe yeah we will also enforce a not null condition on DB schema
