### ISSUE TITLE
Page size needs to be passed by query param to get all items catalogue API

### ISSUE THREAD

**Issue by ub0005** [NASA-IMPACT/HLS-Transfer-Catalog#13]
Page size needs to be passed by query param in fetching all catalog items API

**Why**: We need to give the flexibility to airflow to decide on how many records it can fetch from the catalog service

**Priority** : Low

cc: @NISH1001 @DImuthuUpe @smarru

**Comment by NISH1001** [comment]
Re:
This is a low priority.

**Comment by ub0005** [comment]
Working on this to pass the required_number_of_records as a query parameter
PR: https://github.com/NASA-IMPACT/HLS-Transfer-Catalog/pull/28

cc: @DImuthuUpe @smarru

**Comment by ub0005** [comment]
Closing this issue as we implemented this feature and its working as expected.

cc: @DImuthuUpe @freitagb @smarru
