### ISSUE TITLE
Removing the JWT Authentication logic

### ISSUE THREAD

**Issue by ub0005** [NASA-IMPACT/HLS-Transfer-Catalog#18]
Since the catalog service is going to be deployed in a private subnet.

Removing the JWT Authentication logic.

**Comment by ub0005** [comment]
@DImuthuUpe I remember we discussed that we no longer needed the JWT Authentication of catalog APIs in one of our meetings.

Can you please confirm the same?

If not required, I would like to ahead do some clean-up.

cc: @freitagb @smarru

**Comment by DImuthuUpe** [comment]
@ub0005 It is better if there is a JWT Authentication but there should be a proper identity provider to back this up rather than using hard-coded username-password pairs. However, this service runs inside a private subnet, so authentication is not  a major requirement.

**Comment by ub0005** [comment]
https://github.com/NASA-IMPACT/HLS-Transfer-Catalog/pull/19

cc: @xhagrg @NISH1001
