### ISSUE TITLE
Enhancement: Create a new endpoint to archive the transferred files in catalogue database

### ISSUE THREAD

**Issue by ub0005** [NASA-IMPACT/HLS-Transfer-Catalog#30]
This task is created to archive the transferred records to an archive table so that airflow (orchestration engine)can query up the catalog database table quickly to fetch the records.

- Create a new table called catalogue_catalogue_archive_item
- Create an API with query param as container name which can archive the files belonging to this container
- Have a check for an invalid container name
- Have a check if all files belonging to this container got transferred successfully.

@DImuthuUpe please feel free to update this task description if needed.

cc: @smarru @freitagb

**Comment by DImuthuUpe** [comment]
@ub0005 all sound great. Thanks.  Can you create the PR with the branch you are working on? I tested it locally and it works perfectly

**Comment by ub0005** [comment]
Pr:https://github.com/NASA-IMPACT/HLS-Transfer-Catalog/pull/31
@DImuthuUpe

**Comment by ub0005** [comment]
Closing this issue as we implemented this feature and its working as expected.

cc: @DImuthuUpe @freitagb @smarru
